services:
  postgres:
    image: postgres:16
    container_name: securebank-postgres
    environment:
      POSTGRES_DB: securebankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - securebank_postgres_data:/var/lib/postgresql/data

  securebank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: securebank-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/securebankdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8081"

volumes:
  securebank_postgres_data:
