name: SecureBank CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant Gradle Permission
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Application
        run: ./gradlew build -x test

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t yigitsancar/securebank:latest .

      - name: Push Docker Image
        run: docker push yigitsancar/securebank:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ~/deploy-securebank.sh

            export KUBECONFIG=$HOME/.kube/config

            kubectl rollout restart deployment/securebank-backend -n securebank
            kubectl rollout status deployment/securebank-backend -n securebank
